__yigaosuRoutes([
{"From":"广东三水站","To":"广东高赞站","FromCoords":"23.171484, 112.90296","ToCoords":"22.763522, 113.205753","DrivingDistance":70941},
{"From":"广东三龙湾站","To":"广东容桂站","FromCoords":"23.00497, 113.223008","ToCoords":"22.743909, 113.313983","DrivingDistance":34508},
{"From":"广东三龙湾站","To":"广东碧江站","FromCoords":"23.00497, 113.223008","ToCoords":"22.942295, 113.253953","DrivingDistance":8423},
{"From":"广东三龙湾站","To":"广东顺德站","FromCoords":"23.00497, 113.223008","ToCoords":"22.830734, 113.305634","DrivingDistance":22027},
{"From":"广东东升站","To":"广东中山西站","FromCoords":"22.602826, 113.310143","ToCoords":"22.560179, 113.320837","DrivingDistance":7495},
{"From":"广东东升站","To":"广东港口站","FromCoords":"22.602826, 113.310143","ToCoords":"22.588857, 113.395634","DrivingDistance":9583},
{"From":"广东东沙站","To":"广东顺德站","FromCoords":"23.056442, 113.255247","ToCoords":"22.830734, 113.305634","DrivingDistance":27905},
{"From":"广东中山西站","To":"广东容桂站","FromCoords":"22.559925, 113.321285","ToCoords":"22.743909, 113.313983","DrivingDistance":21752},
{"From":"广东丹灶站","To":"广东冲鹤站","FromCoords":"23.051955, 112.90585","ToCoords":"22.803658, 113.192787","DrivingDistance":52658},
{"From":"广东五沙站","To":"广东东沙站","FromCoords":"22.818399, 113.348866","ToCoords":"23.056357, 113.255697","DrivingDistance":29877},
{"From":"广东五沙站","To":"广东佛平路站","FromCoords":"22.818399, 113.348866","ToCoords":"23.026337, 113.173216","DrivingDistance":36308},
{"From":"广东伦教站","To":"广东丹灶站","FromCoords":"22.86425, 113.253817","ToCoords":"23.052077, 112.905602","DrivingDistance":54658},
{"From":"广东伦教站","To":"广东海五路站","FromCoords":"22.86425, 113.253817","ToCoords":"23.048931, 113.172431","DrivingDistance":30137},
{"From":"广东伦教站","To":"广东虎门站","FromCoords":"22.864585, 113.257896","ToCoords":"22.778574, 113.702807","DrivingDistance":53989},
{"From":"广东佛平路站","To":"广东冲鹤站","FromCoords":"23.028721, 113.172498","ToCoords":"22.803658, 113.192787","DrivingDistance":25335},
{"From":"广东佛平路站","To":"广东勒流站","FromCoords":"23.028721, 113.172498","ToCoords":"22.862208, 113.182668","DrivingDistance":18705},
{"From":"广东佛平路站","To":"广东北滘站","FromCoords":"23.028721, 113.172498","ToCoords":"22.906177, 113.185648","DrivingDistance":15190},
{"From":"广东佛平路站","To":"广东广佛新干线站","FromCoords":"23.040883, 113.172563","ToCoords":"23.086912, 113.168126","DrivingDistance":5120},
{"From":"广东佛平路站","To":"广东花卉大道站","FromCoords":"23.028721, 113.172498","ToCoords":"22.976422, 113.177","DrivingDistance":5850},
{"From":"广东佛平路站","To":"广东西龙站","FromCoords":"23.028721, 113.172498","ToCoords":"22.998396, 113.172684","DrivingDistance":3358},
{"From":"广东佛平路站","To":"广东顺德站","FromCoords":"23.028721, 113.172498","ToCoords":"22.830734, 113.305634","DrivingDistance":31974},
{"From":"广东佛平路站","To":"广东高赞站","FromCoords":"23.028721, 113.172498","ToCoords":"22.763522, 113.205753","DrivingDistance":29985},
{"From":"广东冲蒌站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东勒流站","To":"广东伦教站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东勒流站","To":"广东佛平路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东勒流站","To":"广东广佛新干线站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东勒流站","To":"广东海五路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东勒流站","To":"广东潭洲会展站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东华快土华站","To":"广东永汉站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东华快黄埔站","To":"广东白花站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东华阳路站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东南头站西线二期","To":"广东容桂站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东南头站西线二期","To":"广东界涌站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东南屏站","To":"广东容桂站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东厚街站","To":"广东乐从站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东台城站","To":"广东三江站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东大学城站","To":"广东细沥站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东大沥站","To":"广东海陵岛站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东季华东站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东季华东站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东季华东站","To":"广东花卉大道站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东季华东站","To":"广东西龙站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东季华东站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东容桂站","To":"广东南头站西线二期","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东容桂站","To":"广东南屏站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广佛新干线站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广佛新干线站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广佛新干线站","To":"广东小榄北站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广佛新干线站","To":"广东西龙站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广佛新干线站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广州南站","To":"广东东沙主线站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东广花站","To":"广东谢边站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东徐闻港站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东新桂路站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东新桂路站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东桂丹站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东桂丹站","To":"广东黄圃B站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东棠下站","To":"广东上川站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东横江站","To":"广东海五路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东水边站","To":"广东新市站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东永汉站","To":"广东番禺大桥站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东浔峰洲站","To":"广东江口站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东佛平路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东广佛新干线站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东花卉大道站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东西龙站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东顺德站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海五路站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海洲站","To":"广东清远西站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海陵岛站","To":"广东陈山站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东海鸥岛站","To":"广东细沥站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东清远站","To":"广东清远西站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东清远西站","To":"广东吉利大道站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东潭洲会展站","To":"广东冲鹤站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东潭洲会展站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东潭洲会展站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东潭洲会展站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东环镇西站","To":"广东冲鹤站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东碧江站","To":"广东三龙湾站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东碧江站","To":"广东南丫匝道站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东碧江站","To":"广东顺德站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东细沥站","To":"广东大学城站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西华站","To":"广东潭洲会展站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西樵站西二环南","To":"广东龙江站南二环","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东佛平路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东勒流站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东北滘站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东季华东站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东广佛新干线站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东海五路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东西龙站","To":"广东高赞站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东金山湖站","To":"广东顺德站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东金门站","To":"广东广海站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东陈山站","To":"广东徐闻港站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东陈山站","To":"广东谢边站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东五沙站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东亚运城站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东佛平路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东南丫站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东季华东站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东广州南站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东海五路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东顺德站","To":"广东碧江站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东飞来峡站","To":"广东太和站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东三水站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东佛平路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东冲鹤站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东南丫匝道站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东季华东站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东小榄北站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东广佛新干线站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东海五路站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东海洲站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东潭洲会展站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东睦洲站","FromCoords":"","ToCoords":"","DrivingDistance":0},
{"From":"广东高赞站","To":"广东西龙站","FromCoords":"","ToCoords":"","DrivingDistance":0},
null
])
